version: "3.8"

services:
    cache:
        image: redis:latest
        ports:
            - target: 6379

    proxy:
        image: nginx:latest
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - server
        ports:
            - target: 3000
              published: 3000
              mode: host
    server:
        image: niskii/niskii-dot-dev_api:latest
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - REDIS_HOST=cache
            - REDIS_PORT=6379
            - ENV_PATH=/run/secrets/API_ENV_FILE
        secrets:
            - API_ENV_FILE
        ports:
            - target: 80
        depends_on:
            - cache
        deploy:
            update_config:
                parallelism: 2
                order: start-first
                failure_action: rollback
                delay: 20s
            rollback_config:
                parallelism: 0
                order: stop-first
        healthcheck:
            test: curl --fail http://localhost/health || exit 1
            interval: 10s
            retries: 5
            start_period: 5s
            timeout: 10s

secrets:
    API_ENV_FILE:
        file: ./.env