name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the image and push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Image
        run: |
            docker-compose -f docker-compose.yml build server

      - name: Push Image to the registry
        run: |
            docker-compose -f docker-compose.yml push